[ci skip] Deleting gitops release files
Signed-off-by: surabhi-dudhediya <surabhi.dudhediya@accenture.com>

diff --git a/platforms/r3-corda-ent/charts/node-initial-registration/templates/job.yaml b/platforms/r3-corda-ent/charts/node-initial-registration/templates/job.yaml
--- a/platforms/r3-corda-ent/charts/node-initial-registration/templates/job.yaml
+++ b/platforms/r3-corda-ent/charts/node-initial-registration/templates/job.yaml
@@ -401,6 +401,16 @@ spec:
                   (echo '{"data": {"nodekeystore.jks": "'; base64 ${BASE_DIR}/certificates/nodekeystore.jks; echo '"}}') | curl -H "X-Vault-Token: ${VAULT_TOKEN}" -d @- ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/certs/nodekeystore
                   (echo '{"data": {"sslkeystore.jks": "'; base64 ${BASE_DIR}/certificates/sslkeystore.jks; echo '"}}') | curl -H "X-Vault-Token: ${VAULT_TOKEN}" -d @- ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/certs/sslkeystore
                   (echo '{"data": {"truststore.jks": "'; base64 ${BASE_DIR}/certificates/truststore.jks; echo '"}}') | curl -H "X-Vault-Token: ${VAULT_TOKEN}" -d @- ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/certs/truststore
+
+                  LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/certs/nodekeystore | jq -r 'if .errors then . else . end')
+                  TLS_NODEKEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data[ "nodekeystore.jks" ]' 2>&1)
+                  # get sslkeystore.jks from vault
+                  LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/certs/sslkeystore | jq -r 'if .errors then . else . end')
+                  TLS_SSLKEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data[ "sslkeystore.jks" ]' 2>&1)
+                  # get truststore.jks from vault
+                  LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/certs/truststore | jq -r 'if .errors then . else . end')
+                  TLS_TRUSTSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data[ "truststore.jks" ]' 2>&1)
+
                   if [ "$FLOAT_VAULT_ADDR" != "" ]
                   then
                     echo "Getting vault token for float vault and putting certificates in it.."
@@ -409,20 +419,35 @@ spec:
                     # Put in the certs in float vault is firewall is enabled
                     (echo '{"data": {"sslkeystore.jks": "'; base64 ${BASE_DIR}/certificates/sslkeystore.jks; echo '"}}') | curl -H "X-Vault-Token: ${VAULT_TOKEN_FLOAT}" -d @- ${FLOAT_VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/certs/sslkeystore
                     (echo '{"data": {"truststore.jks": "'; base64 ${BASE_DIR}/certificates/truststore.jks; echo '"}}') | curl -H "X-Vault-Token: ${VAULT_TOKEN_FLOAT}" -d @- ${FLOAT_VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/certs/truststore
+
+                    LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${FLOAT_VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/certs//truststore | jq -r 'if .errors then . else . end')
+                    FLOAT_TRUSTSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data[ "truststore.jks" ]' 2>&1)
+                    LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${FLOAT_VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/certs//sslkeystore | jq -r 'if .errors then . else . end')
+                    FLOAT_SSL=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data[ "sslkeystore.jks" ]' 2>&1)
+
+                    if [ "$FLOAT_TRUSTSTORE" == "null" ] || [ "$FLOAT_SSL" == "null" ] || [ "$FLOAT_TRUSTSTORE" == "parse error"* ] || [ "$FLOAT_SSL" == "parse error"* ] 
+                    then
+                      echo "certificates read or write fail"
+                      sleep {{ $.Values.healthcheck.readinessthreshold  }}
+                      if [ "$COUNTER" -ge {{ $.Values.vault.retries }} ]
+                      then
+                        echo "Retry attempted $COUNTER times, certificates have not been saved"
+                        exit 1
+                      fi
+                    fi
                   fi
-                  break
-                else
-                  echo "certificates are not ready, sleeping for the defined time"
-                  sleep {{ $.Values.vault.retryInterval }}
-                  COUNTER=`expr "$COUNTER" + 1`
+                  if [ "$TLS_NODEKEYSTORE" == "null" ] || [ "$TLS_SSLKEYSTORE" == "null" ] || [ "$TLS_TRUSTSTORE" == "null" ] || [[ "$TLS_NODEKEYSTORE" == "parse error"* ]] || [[ "$TLS_SSLKEYSTORE" == "parse error"* ]] || [[ "$TLS_TRUSTSTORE" == "parse error"* ]]
+                  then
+                    echo "certificates write or read fail"
+                    sleep {{ $.Values.healthcheck.readinessthreshold  }}
+                    if [ "$COUNTER" -ge {{ $.Values.vault.retries }} ]
+                    then
+                      echo "Retry attempted $COUNTER times, certificates have not been saved"
+                      exit 1
+                    fi
+                  fi
                 fi
             done
-            if [ "$COUNTER" -gt {{ $.Values.vault.retries }} ]
-            then
-                echo "Retry attempted $COUNTER times, no files found. Giving up!"
-                exit 1
-                break
-            fi
           volumeMounts:
           - name: node-nodeinfo
             mountPath: /opt/corda/additional-node-infos
